# Generated by Django 3.2 on 2021-10-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211026_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_new',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
